### ISSUE TITLE
npm-merge-driver breaks heroku deployment

### ISSUE THREAD

**Issue by collin** [FullstackAcademy/boilermaker#121]
Steps to reproduce:
```
git clone git@github.com:FullstackAcademy/boilermaker.git break-deploy
cd break-deploy
heroku create
npm run deploy
```

The deploy breaks when it runs `npm-merge-driver install`
```
remote:        > boilermaker@1.0.0 prepare /tmp/build_6d7886aa5046b6f71d822b48cca31e2d
remote:        > npm-merge-driver install
```

Is there some way we can skip this on deploy?

Full error:

```
remote:        > boilermaker@1.0.0 prepare /tmp/build_6d7886aa5046b6f71d822b48cca31e2d
remote:        > npm-merge-driver install
remote:        
remote:        fatal: Not a git repository (or any parent up to mount point /tmp)
remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
remote:        /tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/node_modules/yargs/yargs.js:1100
remote:        else throw err
remote:        ^
remote:        
remote:        Error: Command failed: git rev-parse --git-dir
remote:        fatal: Not a git repository (or any parent up to mount point /tmp)
remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
remote:        
remote:        at checkExecSyncError (child_process.js:603:11)
remote:        at Object.execSync (child_process.js:640:13)
remote:        at findAttributes (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/index.js:184:8)
remote:        at Object.install [as handler] (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/index.js:97:20)
remote:        at Object.runCommand (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/node_modules/yargs/lib/command.js:228:22)
remote:        at Object.parseArgs [as _parseArgs] (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/node_modules/yargs/yargs.js:1013:30)
remote:        at Object.get [as argv] (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/node_modules/yargs/yargs.js:957:21)
remote:        at parseArgs (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/index.js:93:21)
remote:        at Object.<anonymous> (/tmp/build_6d7886aa5046b6f71d822b48cca31e2d/node_modules/npm-merge-driver/index.js:11:3)
remote:        at Module._compile (internal/modules/cjs/loader.js:689:30)
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! boilermaker@1.0.0 prepare: `npm-merge-driver install`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the boilermaker@1.0.0 prepare script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.757YJ/_logs/2018-07-25T15_16_56_199Z-debug.log
```

**Comment by collin** [comment]
I can confirm that removing the `prepare` script from `package.json` does resolve the issue.

**Comment by glebec** [comment]
Ah darn. OK, we can just remove the `npm-merge-driver` commit and `prepare` script for now.
