### ISSUE TITLE
Error upon install

### ISSUE THREAD

**Issue by Yates39** [FullstackAcademy/boilermaker#44]
I've been struggling with my own boilermaker, so I cloned, npm installed and npm started this boilermaker.

This is the response I got:

➜  boilermaker git:(master) npm start

> boilermaker@1.0.0 start /Users/yateswalker/github/boilermakerFromFullstack/boilermaker
> node server

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13
Google client ID / secret not found. Skipping Google OAuth.
Mixing it up on port 8080
GET / 200 10.743 ms - 320
{ Error: Not found
    at app.use.use (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/server/index.js:64:19)
    at Layer.handle [as handle_request] (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:317:13)
    at /Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:421:12)
    at onstat (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:123:15) status: 404 }
Error: Not found
    at app.use.use (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/server/index.js:64:19)
    at Layer.handle [as handle_request] (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:317:13)
    at /Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:421:12)
    at onstat (/Users/yateswalker/github/boilermakerFromFullstack/boilermaker/node_modules/send/index.js:727:26)
    at FSReqWrap.oncomplete (fs.js:123:15)
GET /bundle.js 404 8.457 ms - 9
GET /style.css 200 12.671 ms - 202

**Comment by glebec** [comment]
`npm start` is not the correct command. You will get a "Not Found" because you are not building your bundle.js. The correct command is `npm run start-dev`, which includes running Webpack as a build tool. `npm start` is only meant to be used by the deployment server (which will have the bundle pushed to it through a deploy script or CI service).
